#
# Configuration data template for 'WindowsServiceMonitor.PS'
#
# Generated by: June Castillote
#
# Generated on: 7/15/2024
#
# Template version 1.0
#
@{
    # Specify the list of services.
    # Use the service name or display name or a mix of both.
    # Required: True
    Service                     = @()

    # Specify the interval in which the service check repeats.
    # Use 0 to run the service check only once and the monitor will exit immediately.
    # Do not set a negative value.
    # Required: True
    IntervalInSeconds           = 60

    # The organization name to appear in the report.
    # Required: True
    OrganizationName            = ''

    # The directory where any output files will be stored.
    # If left blank, the default will be the value of the $env:temp environment variable for the running account context
    # -- ie. 'C:\Windows\TEMP' if the PowerShell host is running under the 'nt authority\system' account context.
    # -- ie. 'C:\Users\<username>\AppData\Local\Temp' if the PowerShell host is running under a user account context.
    OutputDirectory             = ''

    # Define the number of latest report or output files to be kept in the OutputDirectory.
    # For example: If the value is 30, only the newest 30 files will be retained bsaed on creation date.
    # The value must be higher than 0.
    # Required: True
    MaxNumberOfReportsToKeep    = 6

    # Set to $true to notify only when services are not running.
    # Set to $false to notify on all service status.
    NotifyIfNotRunningOnly      = $true

    # Specify the type if email method to use.
    # * NONE = Email notification is disabled.
    # * SMTP = Email notification via SMTP relay (SMTP configuration will be required.)
    # * MSGRAPH = Email notification via Microsoft Graph API (Microsoft Graph API PowerShell module is required.)
    # NOTE: This module does not handle the connection and authentication to Microsoft Graph API PowerShell.
    SendEmailNotificationMethod = 'NONE'

    # NOTE: If the SendEmailNotificationMethod is None, the SmtpConfiguration settings will be ignored.
    #
    # SmtpServer: The SMTP server's FQDN or IP address.
    # Port: The SMTP server's port number.
    # UseSSL: Specifies whether the SMTP service requires SSL/TLS, which is typically the case for cloud-hosted SMTP hosts (ie. Exchange Online, SendGrid)
    # CredentialFile: The full path of the encrypted credential file.
    # --> You can create the credential file by running Get-Credential | Export-CliXml <filename.xml>.
    # --> The credential file must be created under the same account that the script will run.
    #   --> Example: If the script will run under USER_A's account, then USER_A must be the one to create the encrypted credential file.
    # From: The sender's email address
    # To: The TO recipients' email address. REQUIRED: TRUE
    # Cc: The Cc recipients' email address. REQUIRED: FALSE
    # Bcc: The Bcc recipients' email address. REQUIRED: FALSE

    SmtpConfiguration           = @{
        SmtpServer     = ''
        SmtpPort       = 25
        SmtpSSLEnabled = $false
        CredentialFile = ''
        MailFrom       = ''
        MailTo         = @()
        MailCc         = @()
        MailBcc        = @()
    }
}